var options=document.getElementById('btn-group');
var btn=document.getElementById('btn');
if(document.getElementById('channelList')){var channelList=document.getElementById('channelList')};
if(document.getElementById('searchList')){var searchList=document.getElementById('searchList')};
if(document.getElementById('searchList')){var urlList=document.getElementById('urlList')};
var list=document.getElementById('list');
var topdiv=document.getElementById('top');
var loading=document.getElementById('loading');
const s2t = OpenCC.Converter({ from: 'cn', to: 'tw' });
